import { resolveReceivingPurchase } from "./receiving-lots.js";
export function renderReceivingHistory(state, {esc, fmt}) {
  const variants = state.products.flatMap(product => product.variants.map(variant => ({product,variant})));
  const label = ({product,variant}) => `${product.name} · ${variant.color || '-'} · ${variant.size || '-'}${variant.chestInches ? ` · อก ${variant.chestInches}` : ''}${variant.lengthInches ? ` · ยาว ${variant.lengthInches}` : ''}`;
  return state.transactions.filter(tx => tx.receivingLot).map(tx => {
    const rows = tx.receivingLot.items.map((stored,index) => {
      const item = {...stored, ...resolveReceivingPurchase(state,stored)};
      const pending = state.pendingOrders.find(order => order.id === item.id);
      const preorder = state.preorders.find(order => order.id === item.id);
      const remaining = item.kind === 'stock' ? pending?.qty || 0 : (preorder?.qty || 0) - (preorder?.receivedQty || 0);
      const matches = variants.filter(({product,variant}) => item.label === `เข้าสต็อก · ${product.name} · ${variant.color || ''} ${variant.size || ''}`);
      return `<div class="receipt-existing-row"><div class="receipt-item-heading"><strong>${esc(item.label.replace(/^เข้าสต็อก · /,''))}</strong><button type="button" class="btn btn-ghost btn-sm" data-receipt-remove="${index}">คืนของ</button></div><div class="receipt-item-fields"><div class="field"><label>รับแล้ว (ชิ้น)</label><input name="qty" type="number" min="0" max="${item.qty + remaining}" step="1" value="${item.qty}" required></div><span class="hint">${item.purchase ? `ต้นทุน ${fmt(item.purchase.cost)}/ชิ้น` : 'ยังไม่มีต้นทุนเดิม'}${remaining ? ` · รอรับอีก ${remaining} ชิ้น` : ''}</span></div>${item.kind === 'stock' && (!item.purchase || !item.variantId) ? `<div class="receipt-legacy form-grid"><div class="field"><label>เสื้อรายการนี้</label><select name="legacyVariant"><option value="">เลือกเสื้อ</option>${variants.map(entry=>`<option value="${esc(entry.variant.id)}" ${matches.length===1 && matches[0].variant.id===entry.variant.id ? 'selected' : ''}>${esc(label(entry))}</option>`).join('')}</select></div><div class="field"><label>ต้นทุนเดิม/ชิ้น</label><input name="legacyCost" type="number" min="0" step="any" placeholder="กรอกครั้งเดียว" ${item.purchase ? `value="${item.purchase.cost}"` : ''}></div></div>` : ''}</div>`;
    }).join('');
    return `<details class="receipt-lot"><summary>${esc(tx.date)} · ${esc(tx.receivingLot.items[0]?.label.replace(/^เข้าสต็อก · /,'') || 'คืนของหมดแล้ว')}<small>${tx.receivingLot.items.reduce((sum,item)=>sum+item.qty,0)} ชิ้น · ค่าส่ง ${fmt(tx.amount)}</small></summary><form data-receipt-edit="${esc(tx.id)}" data-expected="${esc(JSON.stringify(tx))}">${rows || '<p class="hint">คืนของในล็อตนี้หมดแล้ว</p>'}<div class="receipt-additions"></div><button type="button" class="btn btn-ghost" data-receipt-add>+ เพิ่มจากรอรับ</button><div class="field receipt-total"><label>ค่าส่งรวม (บาท)</label><input name="total" type="number" min="0" step="0.01" value="${tx.amount}" required></div><details class="receipt-advanced"><summary>แบ่งค่าส่งเอง</summary><div class="field"><label>วิธีแบ่ง</label><select name="mode"><option value="quantity">แบ่งตามจำนวน</option><option value="manual" selected>ใช้ยอดเดิม / ใส่เอง</option></select></div><div class="receipt-shares">${tx.receivingLot.items.map(item=>`<div class="field"><label>${esc(item.label.replace(/^เข้าสต็อก · /,''))}</label><input name="share" type="number" min="0" step="0.01" value="${item.share}" required></div>`).join('')}</div></details><button class="btn btn-gold" type="submit">บันทึก</button></form></details>`;
  }).join('') || '<p class="hint">ยังไม่มีประวัติรับของ</p>';
}
