const {expandAds}=require('./helpers');
const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
function seed(){const s=inventory();s.adCampaigns=[{id:'ad',name:'แบ่งแอด',productId:'product-1',channel:'Facebook',status:'active',startDate:today(),endDate:today(),targetQty:10,reservePercent:20,reservePerUnit:50,note:'',url:''}];return s;}
test('per-unit reserve saves sale overrides and preserves history after campaign edits',async({page})=>{
 await boot(page,seed());await nav(page,'sell');const card=page.locator('[data-sale-card]').first();await card.locator('.sell-ad-campaign').selectOption('ad');await card.locator('.sell-qty').fill('2');await expect(card.locator('.sell-ad-preview')).toContainText('฿100');await card.locator('.sell-ad-reserve').fill('35.25');await expect(card.locator('.sell-ad-preview')).toContainText('฿70.5');await card.locator('.sell-submit').click();await expectSaved(page,s=>s.transactions.some(t=>t.adReservePerUnit===35.25));
 await nav(page,'ads');await expandAds(page);await expect(page.locator('.ad-reserve strong')).toContainText('฿70.5');await expandAds(page);await page.locator('.ad-edit-details > summary').click();await page.locator('.ad-edit-form [name="reservePerUnit"]').fill('80');await page.locator('.ad-edit-form button').click();await expectSaved(page,s=>s.adCampaigns[0].reservePerUnit===80);await expect(page.locator('.ad-reserve strong')).toContainText('฿70.5');
 const result=await page.evaluate(async()=>{const {adMetrics,validateAdsBackup}=await import('/js/ads.js');const s=structuredClone(window.__testDB);const valid=validateAdsBackup(s.adCampaigns,s.transactions,s.products);s.transactions.find(t=>t.adReservePerUnit!=null).adReservePerUnit=-1;return valid&&!validateAdsBackup(s.adCampaigns,s.transactions,s.products);});expect(result).toBe(true);
});
test('fixed reserves include installments, exclude cancellations, accept zero, and use defaults',async({page})=>{
 await boot(page,seed());const result=await page.evaluate(async()=>{const {adMetrics,applyAdAction}=await import('/js/ads.js');const s=structuredClone(window.__testDB),c=s.adCampaigns[0];s.transactions=[{id:'sale',type:'installment',category:'ขายสินค้า',productId:'variant-1',stockProductId:'product-1',amount:500,paidAmount:0,profit:200,qty:2,date:c.startDate}];const linked=applyAdAction(s,{type:'link',campaignId:c.id,expected:JSON.stringify(c),transactionId:'sale',expectedTransaction:JSON.stringify(s.transactions[0])},'x',c.startDate);const a=adMetrics(c,linked.transactions,c.startDate).reserve;linked.transactions[0].adReservePerUnit=0;const b=adMetrics(c,linked.transactions,c.startDate).reserve;linked.transactions[0].category='ขายสินค้ายกเลิก';const d=adMetrics(c,linked.transactions,c.startDate).reserve;return [a,b,d];});expect(result).toEqual([100,0,0]);
});
