const {expandAds}=require('./helpers');
const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
const offset=(n)=>new Date(Date.parse(today())+n*86400000).toISOString().slice(0,10);
function seed(){const s=inventory();s.adWallet=[];s.adCampaigns=[{id:'ad-1',name:'แอดอัตโนมัติ',productId:'product-1',channel:'Facebook',status:'active',startDate:offset(-3),endDate:'',runMode:'until_budget',budget:0,dailyBudget:100,targetQty:10,reservePercent:20,note:'',url:''}];return s;}
async function topup(page,amount,date){await expandAds(page);await page.locator('.ad-campaign-topup > summary').click();const f=page.locator('.ad-campaign-topup-form');await f.locator('[name="amount"]').fill(String(amount));await f.locator('[name="date"]').fill(date);await f.locator('button').click();}
test('backdated topup deducts three completed days from wallet once; repeat topup does not double charge',async({page})=>{
 await boot(page,seed());await nav(page,'ads');await expandAds(page);await topup(page,500,offset(-3));await expectSaved(page,s=>s.transactions.length===3);let db=await snapshot(page);expect(db.transactions.map(t=>t.amount)).toEqual([100,100,100]);expect(db.transactions.every(t=>t.adAutomatic&&t.adWalletFunded)).toBe(true);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿200');await expect(page.locator('[data-ad-id] .ad-metrics')).not.toContainText('งบคงเหลือ');
 await topup(page,200,offset(-2));await expectSaved(page,s=>s.adWallet.length===2);db=await snapshot(page);expect(db.transactions).toHaveLength(3);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿400');await expect(page.locator('[data-ad-id] .ad-metrics')).not.toContainText('งบคงเหลือ');await nav(page,'home');await expect(page.locator('.expense-stat')).toContainText('฿'+db.transactions.filter(t=>t.date.startsWith(today().slice(0,7))).reduce((sum,t)=>sum+t.amount,0));
 const result=await page.evaluate(async date=>{const {reconcileAutomaticAds}=await import('/js/ads.js');const state=structuredClone(window.__testDB);return JSON.stringify(reconcileAutomaticAds(state,date).transactions)===JSON.stringify(state.transactions);},today());expect(result).toBe(true);
});
test('opening existing backdated deposits catches up and manual daily cost replaces automatic cost',async({page})=>{
 const s=seed();s.adCampaigns[0].budget=500;s.adWallet=[{id:'fund',amount:500,date:offset(-3),note:'',campaignId:'ad-1',budgetIncrease:500}];await boot(page,s);await expectSaved(page,s=>s.transactions.length===3);await nav(page,'ads');await expandAds(page);await expandAds(page);await page.locator('.ad-spend-details > summary').click();const f=page.locator('.ad-spend-form');await f.locator('[name="amount"]').fill('65');await f.locator('[name="date"]').fill(offset(-2));await f.locator('button').click();await expectSaved(page,s=>s.transactions.some(t=>t.amount===65));let db=await snapshot(page);expect(db.transactions.filter(t=>t.date===offset(-2))).toHaveLength(1);expect(db.transactions.reduce((sum,t)=>sum+t.amount,0)).toBe(265);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿235');
 await expandAds(page);await page.locator('.ad-spend-details > summary').click();await page.locator('[data-ad-remove-spend]:not([data-ad-remove-spend^="ad-auto-"])').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.length===2 && s.transactions.every(t=>t.adAutomatic));await expect(page.locator('[data-wallet-balance]')).toHaveText('฿300');
});
test('funding dates, end dates, shared credit limit automatic deductions',async({page})=>{
 await boot(page,inventory());const result=await page.evaluate(async()=>{const {reconcileAutomaticAds,adWalletMetrics}=await import('/js/ads.js');const c={id:'a',name:'A',productId:'product-1',channel:'fb',status:'active',startDate:'2026-01-01',endDate:'2026-01-03',runMode:'dated',budget:250,dailyBudget:100,targetQty:1,reservePercent:0,note:'',url:''};const state={adCampaigns:[c,{...c,id:'b',budget:500}],adWallet:[{id:'w',date:'2026-01-02',amount:350,note:''}],transactions:[]};const first=reconcileAutomaticAds(state,'2026-01-06');return {tx:first.transactions,wallet:adWalletMetrics(first.adWallet,first.transactions),again:reconcileAutomaticAds({...state,...first},'2026-01-07').transactions};});expect(result.tx.map(t=>t.amount)).toEqual([50,100,100,100]);expect(result.tx.every(t=>['2026-01-02','2026-01-03'].includes(t.date))).toBe(true);expect(result.wallet.balance).toBe(0);expect(result.again).toEqual(result.tx);
});
test('rate edits, pauses and resumes preserve past days and do not backfill paused dates',async({page})=>{
 await boot(page,inventory());const result=await page.evaluate(async()=>{const {reconcileAutomaticAds,applyAdAction}=await import('/js/ads.js');const c={id:'a',name:'A',productId:'product-1',channel:'fb',status:'active',startDate:'2026-01-01',endDate:'',runMode:'until_budget',budget:1000,dailyBudget:100,targetQty:1,reservePercent:0,note:'',url:''};let s={products:window.__testDB.products,adCampaigns:[c],adWallet:[{id:'w',date:'2026-01-01',amount:1000,note:''}],transactions:[]};s={...s,...reconcileAutomaticAds(s,'2026-01-03')};const edit=(date,values)=>{s={...s,...applyAdAction(s,{type:'edit',campaignId:'a',expected:JSON.stringify(s.adCampaigns[0]),values:{...s.adCampaigns[0],...values}},'edit',date)};};edit('2026-01-03',{dailyBudget:50});edit('2026-01-04',{status:'paused'});edit('2026-01-06',{status:'active'});s={...s,...reconcileAutomaticAds(s,'2026-01-07')};return s.transactions.map(t=>[t.date,t.amount]);});expect(result).toEqual([['2026-01-06',50],['2026-01-03',50],['2026-01-02',100],['2026-01-01',100]]);
});
test('automatic costs retain historical product shares after new products attach',async({page})=>{
 await boot(page,inventory());const result=await page.evaluate(async()=>{const {reconcileAutomaticAds,applyAdAction}=await import('/js/ads.js');let s={products:[...window.__testDB.products,{...window.__testDB.products[0],id:'p2'}],adCampaigns:[{id:'a',name:'A',productId:'product-1',channel:'fb',status:'active',startDate:'2026-01-01',endDate:'',runMode:'until_budget',budget:1000,dailyBudget:100,targetQty:1,reservePercent:0,note:'',url:''}],adWallet:[{id:'w',date:'2026-01-01',amount:1000,note:''}],transactions:[]};s={...s,...reconcileAutomaticAds(s,'2026-01-02')};s={...s,...applyAdAction(s,{type:'edit',campaignId:'a',expected:JSON.stringify(s.adCampaigns[0]),values:{...s.adCampaigns[0],productIds:['product-1','p2']}},'edit','2026-01-02')};return reconcileAutomaticAds(s,'2026-01-03').transactions;});expect(result[1].adAllocations).toEqual([{productId:'product-1',amount:100}]);expect(result[0].adAllocations).toHaveLength(2);
});
test('failed backdated topup preserves input and retry saves all daily costs atomically',async({page})=>{
 await boot(page,seed());await nav(page,'ads');await expandAds(page);await page.evaluate(()=>window.__testSaveError='offline');await topup(page,500,offset(-3));await expect(page.locator('#modal-message')).toContainText('บันทึกไม่สำเร็จ');expect((await snapshot(page)).transactions).toHaveLength(0);await page.locator('#modal-ok-btn').click();await expect(page.locator('.ad-campaign-topup-form [name="amount"]')).toHaveValue('500');await page.evaluate(()=>delete window.__testSaveError);await page.locator('.ad-campaign-topup-form button').click();await expectSaved(page,s=>s.transactions.length===3);expect((await snapshot(page)).adWallet).toHaveLength(1);
});
test('automatic history validates in backup; malformed schedules and generated flags fail',async({page})=>{
 await boot(page,seed());await nav(page,'ads');await expandAds(page);await topup(page,500,offset(-3));await expectSaved(page,s=>s.transactions.length===3);const results=await page.evaluate(async()=>{const {validateAdsBackup}=await import('/js/ads.js');const s=structuredClone(window.__testDB);const valid=()=>validateAdsBackup(s.adCampaigns,s.transactions,s.products);const r=[valid()];s.adCampaigns[0].autoHistory[0].dailyBudget=-1;r.push(valid());s.adCampaigns[0].autoHistory[0].dailyBudget=100;s.transactions[0].adAutomatic='true';r.push(valid());return r;});expect(results).toEqual([true,false,false]);
});
test('open app catches up once after Bangkok midnight and leaves today uncharged',async({page})=>{
 await page.clock.install({time:new Date(today()+'T16:59:30Z')});const s=seed();s.adCampaigns[0].startDate=today();s.adCampaigns[0].budget=500;s.adWallet=[{id:'w',amount:500,date:today(),note:''}];await boot(page,s);await nav(page,'ads');await expandAds(page);expect((await snapshot(page)).transactions).toHaveLength(0);await page.clock.runFor(61000);await expectSaved(page,s=>s.transactions.length===1);expect((await snapshot(page)).transactions[0]).toMatchObject({date:today(),amount:100});await page.clock.runFor(60000);expect((await snapshot(page)).transactions).toHaveLength(1);
});
test('late funding does not pay unfunded earlier dates and deleting it reverses only generated costs',async({page})=>{
 await boot(page,seed());await nav(page,'ads');await expandAds(page);await topup(page,250,offset(-1));await expectSaved(page,s=>s.adWallet.length===1);expect((await snapshot(page)).transactions.map(t=>[t.date,t.amount])).toEqual([[offset(-1),100]]);await expandAds(page);await page.locator('.ad-campaign-topup > summary').click();await page.locator('.ad-campaign-topup [data-ad-remove-topup]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.adWallet.length===0);expect((await snapshot(page)).transactions).toHaveLength(0);expect((await snapshot(page)).adCampaigns[0].budget).toBe(0);
});
