const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
function seed(){const s=inventory();s.adWallet=[];s.adCampaigns=[{id:'ad-1',name:'แอดเสื้อ',productId:'product-1',channel:'Facebook',status:'active',startDate:today(),endDate:'',runMode:'until_budget',budget:100,dailyBudget:50,targetQty:10,reservePercent:20,note:'',url:''}];s.transactions=[{id:'expense',type:'expense',category:'ค่าโฆษณาสินค้า',adCampaignId:'ad-1',date:today(),amount:100,desc:'ค่าแอด'}];return s;}
async function form(page,amount='200'){await page.locator('.ad-campaign-topup > summary').click();const f=page.locator('.ad-campaign-topup-form');await f.locator('[name="amount"]').fill(amount);return f;}
test('campaign topup increases its budget and central credit once and resumes an exhausted campaign',async({page})=>{
 const s=seed();await boot(page,s);await nav(page,'ads');await expect(page.locator('[data-ad-id]')).toHaveAttribute('data-ad-phase','exhausted');const f=await form(page);await expect(f.locator('.ad-topup-preview')).toContainText('งบหลังเติม ฿300');await f.locator('button').click();await expectSaved(page,s=>s.adWallet.length===1);
 let db=await snapshot(page);expect(db.adCampaigns[0].budget).toBe(300);expect(db.adWallet[0]).toMatchObject({campaignId:'ad-1',budgetIncrease:200,amount:200});expect(db.transactions).toEqual(s.transactions);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿200');await expect(page.locator('[data-ad-id]')).toHaveAttribute('data-ad-phase','active');
 await page.locator('.ad-campaign-topup > summary').click();await page.locator('.ad-campaign-topup [data-ad-remove-topup]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.adWallet.length===0);db=await snapshot(page);expect(db.adCampaigns[0].budget).toBe(100);expect(db.transactions).toEqual(s.transactions);await expect(page.locator('[data-ad-id]')).toHaveAttribute('data-ad-phase','exhausted');
});
test('failed topup preserves amount and retry does not duplicate wallet credit or budget',async({page})=>{
 await boot(page,seed());await nav(page,'ads');const f=await form(page,'125.50');await page.evaluate(()=>window.__testSaveError='offline');await f.locator('button').click();await expect(page.locator('#modal-message')).toContainText('บันทึกไม่สำเร็จ');await page.locator('#modal-ok-btn').click();expect((await snapshot(page)).adCampaigns[0].budget).toBe(100);await expect(f.locator('[name="amount"]')).toHaveValue('125.50');
 await page.evaluate(()=>{delete window.__testSaveError;window.__testSaveDelay=100;document.querySelector('.ad-campaign-topup-form').requestSubmit();document.querySelector('.ad-campaign-topup-form').requestSubmit();});await expectSaved(page,s=>s.adWallet.length===1);expect((await snapshot(page)).adCampaigns[0].budget).toBe(225.5);
});
test('stale campaign or invalid amount cannot change credit; linked history protects campaign deletion',async({page})=>{
 await boot(page,seed());await nav(page,'ads');const f=await form(page,'-5');await f.evaluate(f=>f.noValidate=true);await f.locator('button').click();await expect(page.locator('#modal-message')).toContainText('ยอดเติมเงินต้อง');await page.locator('#modal-ok-btn').click();await f.locator('[name="amount"]').fill('50');await page.evaluate(()=>{window.__testDB.adCampaigns[0].budget=150;window.__testSubscribers.adCampaigns(structuredClone(window.__testDB.adCampaigns));});await f.locator('button').click();await expect(page.locator('#modal-message')).toContainText('แคมเปญเปลี่ยนแปลง');await page.locator('#modal-ok-btn').click();expect((await snapshot(page)).adWallet).toHaveLength(0);
 await nav(page,'home');await nav(page,'ads');const refreshed=await form(page,'50');await refreshed.locator('button').click();await expectSaved(page,s=>s.adWallet.length===1);await page.locator('.ad-edit-details > summary').click();await page.locator('[data-ad-delete]').click();await page.locator('#modal-ok-btn').click();await expect(page.locator('#modal-message')).toContainText('ประวัติเติมเงิน');
});
test('backup validates campaign topup references and global deletion reverses the linked budget',async({page})=>{
 await boot(page,seed());await nav(page,'ads');const f=await form(page);await f.locator('button').click();await expectSaved(page,s=>s.adWallet.length===1);await page.locator('.data-tools summary').click();const wait=page.waitForEvent('download');await page.locator('#export-btn').click();const chunks=[];for await(const c of await(await wait).createReadStream())chunks.push(c);const backup=JSON.parse(Buffer.concat(chunks).toString());expect(backup.version).toBe(10);
 const upload=data=>page.locator('#import-input').setInputFiles({name:'topup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await upload(backup);await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.adWallet.length===1);
 for(const mutate of [b=>b.adWallet[0].campaignId='missing',b=>b.adWallet[0].budgetIncrease=99]){const bad=structuredClone(backup);mutate(bad);await upload(bad);await expect(page.locator('#modal-message')).toContainText('ไม่ถูกต้อง');await page.locator('#modal-ok-btn').click();}
 await page.locator('.ad-wallet-details > summary').click();await page.locator('.ad-wallet [data-ad-remove-topup]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.adWallet.length===0);expect((await snapshot(page)).adCampaigns[0].budget).toBe(100);
});
for(const width of [390,1440]) test(`campaign topup controls fit ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});const errors=await boot(page,seed());await nav(page,'ads');const f=await form(page);await f.screenshot({path:`test-results/campaign-topup-${width}.png`});const d=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));expect(d.s).toBeLessThanOrEqual(d.w+1);expect(errors).toEqual([]);
});
