const {expandAds}=require('./helpers');
const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
const ago=n=>new Date(Date.parse(today())-n*86400000).toISOString().slice(0,10);
const campaign=(extra={})=>({id:'ad',name:'เครดิตกลาง',productId:'product-1',channel:'Facebook',status:'active',runMode:'until_budget',startDate:ago(3),endDate:'',dailyBudget:100,targetQty:10,reservePercent:20,note:'',url:'',...extra});
test('budgetless campaign can be created, funded retroactively, edited and backed up',async({page})=>{
 await boot(page);await nav(page,'ads');await expandAds(page);const f=page.locator('#ad-create-form');await expect(f.locator('[name="budget"]')).toHaveCount(0);await f.locator('[name="name"]').fill('ไม่ใช้งบรวม');await f.locator('[name="productId"]').selectOption('product-1');await f.locator('[name="dailyBudget"]').fill('100');await f.locator('[name="startDate"]').fill(ago(3));await f.locator('[name="targetQty"]').fill('10');await f.locator('button').click();await expectSaved(page,s=>s.adCampaigns.length===1);expect((await snapshot(page)).adCampaigns[0].budget).toBeUndefined();
 await expandAds(page);await page.locator('.ad-campaign-topup > summary').click();const topup=page.locator('.ad-campaign-topup-form');await topup.locator('[name="amount"]').fill('500');await topup.locator('[name="date"]').fill(ago(3));await expect(topup.locator('.ad-topup-preview')).toContainText('เครดิตกลางหลังหัก ฿200');await topup.locator('button').click();await expectSaved(page,s=>s.transactions.length===3);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿200');expect((await snapshot(page)).adWallet[0].budgetIncrease).toBeUndefined();
 await expandAds(page);await page.locator('.ad-edit-details > summary').click();await expect(page.locator('.ad-edit-form [name="budget"]')).toHaveCount(0);await page.locator('.ad-edit-form [name="name"]').fill('แก้ไขแล้ว');await page.locator('.ad-edit-form button').click();await expectSaved(page,s=>s.adCampaigns[0].name==='แก้ไขแล้ว');expect((await snapshot(page)).adCampaigns[0].budget).toBeUndefined();
 await page.locator('.data-tools summary').click();const waiting=page.waitForEvent('download');await page.locator('#export-btn').click();const chunks=[];for await(const c of await(await waiting).createReadStream())chunks.push(c);const backup=JSON.parse(Buffer.concat(chunks).toString());expect(backup.adCampaigns[0].budget).toBeUndefined();await page.locator('#import-input').setInputFiles({name:'credit.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#modal-ok-btn').click();await expect(page.locator('#modal-overlay')).not.toHaveClass(/show/);expect((await snapshot(page)).transactions).toHaveLength(3);
});
test('legacy zero campaign budget and zero history base cannot cap auto spending or mark funded campaign exhausted',async({page})=>{
 const s=inventory();s.adCampaigns=[campaign({budget:0,autoHistory:[{date:ago(3),startDate:ago(3),endDate:'',runMode:'until_budget',status:'active',dailyBudget:100,enabled:true,productIds:['product-1'],baseBudget:0}]})];s.adWallet=[{id:'fund',amount:500,date:ago(3),note:''}];await boot(page,s);await expectSaved(page,s=>s.transactions.length===3);await nav(page,'ads');await expandAds(page);await expect(page.locator('[data-ad-id]')).toHaveAttribute('data-ad-phase','active');await expect(page.locator('[data-wallet-balance]')).toHaveText('฿200');await expect(page.locator('.ad-metrics').last()).not.toContainText('งบคงเหลือ');await nav(page,'tasks');await page.locator('#task-filter').selectOption('ads');await expect(page.locator('[data-task-kind="ads"]')).toHaveCount(0);
});
test('multiple campaigns share deposits once and stop only when available credit runs out',async({page})=>{
 const s=inventory();s.adCampaigns=[campaign({id:'a',budget:1}),campaign({id:'b',budget:999999})];s.adWallet=[{id:'fund',amount:350,date:ago(3),note:'',campaignId:'a'}];await boot(page,s);await expectSaved(page,s=>s.transactions.length===4);const db=await snapshot(page);expect(db.transactions.reduce((sum,t)=>sum+t.amount,0)).toBe(350);expect(db.transactions.filter(t=>t.adCampaignId==='a').reduce((sum,t)=>sum+t.amount,0)).toBe(200);expect(db.transactions.filter(t=>t.adCampaignId==='b').reduce((sum,t)=>sum+t.amount,0)).toBe(150);await nav(page,'ads');await expandAds(page);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿0');await expect(page.locator('[data-ad-phase="exhausted"]')).toHaveCount(2);
});
test('deleting legacy linked funding never subtracts a historical campaign budget',async({page})=>{
 const s=inventory();s.adCampaigns=[campaign({startDate:today(),budget:5})];s.adWallet=[{id:'old',amount:200,budgetIncrease:200,campaignId:'ad',date:today(),note:''}];await boot(page,s);await nav(page,'ads');await expandAds(page);await page.locator('.ad-wallet-details > summary').click();await page.locator('.ad-wallet [data-ad-remove-topup]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.adWallet.length===0);expect((await snapshot(page)).adCampaigns[0].budget).toBe(5);await expect(page.locator('[data-wallet-balance]')).toHaveText('฿0');
});
