const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
function seed(installment=false){const s=inventory();s.shipments=[];s.products[0].variants[0].qty=8;s.products[0].variants[0].cost=150;s.transactions=[{id:'sale',type:installment?'installment':'income',category:'ขายสินค้า',deliveryStatus:'pending',date:today(),desc:'เสื้อ M',productId:'variant-1',stockProductId:'product-1',qty:2,unitCost:100,unitPrice:250,amount:500,profit:295,shipping:5,commission:0,...(installment?{paidAmount:75,dueDate:today()}: {})},{id:'shipping',type:'expense',category:'ค่าส่ง',amount:5,date:today(),desc:'ค่าส่ง'}];if(installment)s.transactions.push({id:'payment',type:'income',category:'รับชำระค่าผ่อน',date:today(),amount:75,installmentId:'sale'});return s;}
async function cancel(page){await page.locator('[data-cancel-sale="sale"]').click();await page.locator('#modal-ok-btn').click();}
test('cancelling a pending sale restores stock at weighted cost, removes sales profit and records refunds only after actual payment',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('.cancel-sale-reason').fill('ลูกค้าเปลี่ยนใจ');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');let db=await snapshot(page);expect(db.products[0].variants[0]).toMatchObject({qty:10,cost:140});expect(db.transactions[0]).toMatchObject({category:'ขายสินค้ายกเลิก',amount:500,refundDue:500,refundedAmount:0,cancellationReason:'ลูกค้าเปลี่ยนใจ'});expect(db.transactions).toHaveLength(2);await expect(page.locator('[data-pending-sale]')).toHaveCount(0);
 await nav(page,'report');await expect(page.locator('#report-range-summary .val')).toHaveText(['฿500','฿5','฿495','฿0','฿0','฿0']);await nav(page,'shipments');await page.locator('[data-refund-sale]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.some(t=>t.saleCancellationId==='sale'));db=await snapshot(page);expect(db.transactions[0]).toMatchObject({type:'expense',amount:500,category:'คืนเงินขายยกเลิก'});expect(db.products[0].variants[0].qty).toBe(10);await expect(page.locator('[data-refund-sale]')).toHaveCount(0);
 await nav(page,'tx');await page.locator('[data-txdel="sale"]').click();await expect(page.locator('#modal-message')).toContainText('ยกเลิกการขาย');
});
test('cancelled installments no longer owe money and only collected payments are refundable',async({page})=>{
 await boot(page,seed(true));await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');await expect(page.locator('[data-cancelled-sale]')).toContainText('รอคืนเงิน ฿75');await nav(page,'installment');await expect(page.locator('[data-pay]')).toHaveCount(0);await expect(page.locator('.installment-stats')).toContainText('฿0');await nav(page,'tasks');await expect(page.locator('[data-task-kind="installment"]')).toHaveCount(0);await expect(page.locator('[data-task-kind="shipment"]')).toContainText('รอคืนเงิน ฿75');await page.locator('[data-task-kind="shipment"] button').click();await page.locator('[data-refund-sale]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.some(t=>t.saleCancellationId==='sale' && t.amount===75));await nav(page,'tx');await page.locator('[data-txdel="payment"]').click();await expect(page.locator('#modal-message')).toContainText('ยกเลิกการขาย');
});
test('failed cancellation restores all stores and retry returns inventory only once',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('.cancel-sale-reason').fill('รอแก้ไข');await page.evaluate(()=>window.__testSaveError='offline');await cancel(page);await expect(page.locator('#modal-message')).toContainText('บันทึกไม่สำเร็จ');await page.locator('#modal-ok-btn').click();expect((await snapshot(page)).products[0].variants[0].qty).toBe(8);expect((await snapshot(page)).transactions[0].deliveryStatus).toBe('pending');await expect(page.locator('.cancel-sale-reason')).toHaveValue('รอแก้ไข');await page.evaluate(()=>delete window.__testSaveError);await cancel(page);await expectSaved(page,s=>s.products[0].variants[0].qty===10);await expect(page.locator('[data-cancel-sale]')).toHaveCount(0);
});
test('cancelled sales reject repeated cancellation and shipping; refund cannot be edited as a manual expense',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');
 const messages=await page.evaluate(async date=>{const {applyShipmentAction}=await import('/js/shipments.js');const state=structuredClone(window.__testDB);const base={expectedSales:{sale:JSON.stringify(state.transactions[0])},expectedShipments:JSON.stringify(state.shipments)};return [{type:'cancelSale',saleId:'sale',reason:''},{type:'ship',values:{date,recipient:'',carrier:'',trackingNumber:'',note:'',items:[{saleId:'sale',qty:2}]}}].map(action=>{try{applyShipmentAction(state,{...base,...action},'id',date);return '';}catch(e){return e.message;}});},today());expect(messages.every(Boolean)).toBe(true);expect((await snapshot(page)).products[0].variants[0].qty).toBe(10);
 await page.locator('[data-refund-sale]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions[0].saleCancellationId==='sale');const id=(await snapshot(page)).transactions[0].id;await nav(page,'tx');await expect(page.locator(`[data-txedit="${id}"]`)).toHaveCount(0);await page.locator(`[data-txdel="${id}"]`).click();await expect(page.locator('#modal-message')).toContainText('ยกเลิกการขาย');
});
test('missing stock and concurrently changed sale cannot be cancelled',async({page})=>{
 const s=seed();s.products=[];await boot(page,s);await nav(page,'shipments');await cancel(page);await expect(page.locator('#modal-message')).toContainText('ไม่พบตัวเลือกสินค้า');await page.locator('#modal-ok-btn').click();expect((await snapshot(page)).transactions[0].deliveryStatus).toBe('pending');await page.locator('[data-cancel-sale]').click();await page.evaluate(()=>{window.__testDB.transactions[0].amount=550;window.__testSubscribers.transactions(structuredClone(window.__testDB.transactions));});await page.locator('#modal-ok-btn').click();await expect(page.locator('#modal-message')).toContainText('เปลี่ยนแปลง');expect((await snapshot(page)).transactions[0].deliveryStatus).toBe('pending');
});
test('partially shipped sales cannot be cancelled and cancelled sales cannot ship or cancel twice',async({page})=>{
 const s=seed();s.transactions[0].deliveryStatus='partial';s.shipments=[{id:'parcel',status:'shipped',date:today(),recipient:'',carrier:'',trackingNumber:'',note:'',items:[{saleId:'sale',qty:1}]}];await boot(page,s);await nav(page,'shipments');await expect(page.locator('[data-cancel-sale]')).toHaveCount(0);
 const message=await page.evaluate(async date=>{const {applyShipmentAction}=await import('/js/shipments.js');const state=structuredClone(window.__testDB);try{applyShipmentAction(state,{type:'cancelSale',saleId:'sale',reason:'',expectedSales:{sale:JSON.stringify(state.transactions[0])},expectedShipments:JSON.stringify(state.shipments)},'id',date);return '';}catch(e){return e.message;}},today());expect(message).toContain('ยังไม่ได้ส่ง');expect((await snapshot(page)).products[0].variants[0].qty).toBe(8);
});
test('cancelled ad sales and refund history survive backup; forged refund amounts are rejected',async({page})=>{
 const s=seed();s.adCampaigns=[{id:'ad',name:'แอด',productId:'product-1',channel:'Facebook',status:'active',startDate:today(),endDate:'',runMode:'until_budget',budget:100,targetQty:2,reservePercent:20,note:'',url:''}];s.transactions[0].adCampaignId='ad';await boot(page,s);await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');await page.locator('[data-refund-sale]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions[0].saleCancellationId==='sale');await page.locator('.data-tools summary').click();const waiting=page.waitForEvent('download');await page.locator('#export-btn').click();const chunks=[];for await(const c of await(await waiting).createReadStream())chunks.push(c);const backup=JSON.parse(Buffer.concat(chunks).toString());expect(backup.version).toBe(11);const upload=b=>page.locator('#import-input').setInputFiles({name:'cancel.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await upload(backup);await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions[0].amount===500);const bad=structuredClone(backup);bad.transactions[0].amount=600;await upload(bad);await expect(page.locator('#modal-message')).toContainText('ไม่ถูกต้อง');expect((await snapshot(page)).transactions[0].amount).toBe(500);
});
for(const width of [390,1440])test(`cancellation controls and refund history fit ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});const errors=await boot(page,seed());await nav(page,'shipments');await page.locator('[data-pending-sale]').screenshot({path:`test-results/cancel-pending-${width}.png`});await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');const d=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));expect(d.s).toBeLessThanOrEqual(d.w+1);expect(errors).toEqual([]);});
for (const installment of [false,true]) test(`cancelled ${installment?'installment':'cash'} receipts leave monthly income and can be removed from ledger before refund`,async({page})=>{
 const s=seed(installment);s.transactions.push({id:'other-income',type:'income',category:'รายรับอื่นๆ',amount:40,date:today(),desc:'รายรับอื่น'});
 await boot(page,s);await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');await nav(page,'home');await expect(page.locator('.income-stat')).toContainText('฿40');await expect(page.locator('.expense-stat')).toContainText('฿5');
 await nav(page,'tx');const receipt=installment?'payment':'sale';await page.locator(`[data-txdel="${receipt}"]`).click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.find(t=>t.id===receipt).ledgerDeletedAt);await expect(page.locator(`[data-txdel="${receipt}"]`)).toHaveCount(0);
 await nav(page,'shipments');await expect(page.locator('[data-refund-sale]')).toHaveCount(1);await page.locator('[data-refund-sale]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.some(t=>t.saleCancellationId==='sale'));const db=await snapshot(page);expect(db.products[0].variants[0].qty).toBe(10);expect(db.transactions.find(t=>t.id==='sale').refundedAmount).toBe(installment?75:500);
 await nav(page,'home');await expect(page.locator('.income-stat')).toContainText('฿40');await expect(page.locator('.expense-stat')).toContainText('฿5');await nav(page,'tx');const refund=db.transactions.find(t=>t.saleCancellationId==='sale');await page.locator(`[data-txdel="${refund.id}"]`).click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions.find(t=>t.id===refund.id).ledgerDeletedAt);await expect(page.locator(`[data-txdel="${refund.id}"]`)).toHaveCount(0);
 const valid=await page.evaluate(async()=>{const {validateShipments}=await import('/js/shipments.js');return validateShipments(window.__testDB.shipments,window.__testDB.transactions);});expect(valid).toBe(true);await nav(page,'report');await expect(page.locator('#report-range-summary .val').nth(2)).toHaveText('฿35');
});
test('ledger removal survives backup and rejects hiding unrelated transactions',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');await nav(page,'tx');await page.locator('[data-txdel="sale"]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions[0].ledgerDeletedAt);
 await page.locator('.data-tools summary').click();const waiting=page.waitForEvent('download');await page.locator('#export-btn').click();const chunks=[];for await(const c of await(await waiting).createReadStream())chunks.push(c);const backup=JSON.parse(Buffer.concat(chunks).toString());expect(backup.transactions[0].ledgerDeletedAt).toBe(today());await page.locator('#import-input').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#modal-ok-btn').click();await nav(page,'tx');await expect(page.locator('[data-txdel="sale"]')).toHaveCount(0);
 const valid=await page.evaluate(async date=>{const {validateShipments}=await import('/js/shipments.js');const state=structuredClone(window.__testDB);state.transactions.find(t=>t.id==='shipping').ledgerDeletedAt=date;return validateShipments(state.shipments,state.transactions);},today());expect(valid).toBe(false);
});
test('failed ledger removal can be retried without losing refund or changing stock',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await cancel(page);await expectSaved(page,s=>s.transactions[0].deliveryStatus==='cancelled');await nav(page,'tx');await page.evaluate(()=>window.__testSaveError='offline');await page.locator('[data-txdel="sale"]').click();await page.locator('#modal-ok-btn').click();await expect(page.locator('#modal-message')).toContainText('บันทึกไม่สำเร็จ');expect((await snapshot(page)).transactions[0].ledgerDeletedAt).toBeUndefined();await page.locator('#modal-ok-btn').click();await page.evaluate(()=>delete window.__testSaveError);await page.locator('[data-txdel="sale"]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.transactions[0].ledgerDeletedAt);expect((await snapshot(page)).products[0].variants[0].qty).toBe(10);
});
