const {test,expect}=require('@playwright/test');
const {boot,nav,inventory,snapshot,expectSaved,today}=require('./helpers');
function seed(){const s=inventory();s.shipments=[];s.transactions=[{id:'sale1',type:'income',category:'ขายสินค้า',desc:'เสื้อ M',date:today(),qty:3,amount:750,profit:440,shipping:10,unitCost:100,productId:'variant-1',deliveryStatus:'pending'},{id:'sale2',type:'installment',category:'ขายสินค้า',desc:'เสื้อ L',date:today(),qty:1,amount:200,paidAmount:50,profit:120,shipping:0,productId:'variant-2',deliveryStatus:'pending'}];return s;}
async function send(page){await page.locator('#shipment-submit').click();await page.locator('#modal-ok-btn').click();}
async function editCost(page,amount){await page.locator('.shipment-history-cost').fill(String(amount));await page.locator('[data-shipment-cost]').click();await page.locator('#modal-ok-btn').click();}
test('one parcel attaches several sales, splits cents by quantity and records shipping expense once',async({page})=>{
 const s=seed();await boot(page,s);await nav(page,'shipments');await page.locator('#shipment-select-all').check();await page.locator('#shipment-cost').fill('50.01');await send(page);await expectSaved(page,s=>s.shipments.length===1);const db=await snapshot(page);expect(db.shipments[0].shippingCost).toBe(50.01);expect(db.shipments[0].items.map(i=>i.shippingShare)).toEqual([37.51,12.5]);expect(db.transactions.filter(t=>t.shipmentId)).toHaveLength(1);expect(db.transactions.find(t=>t.id==='sale1')).toMatchObject({shipping:47.51,profit:402.49,deliveryStatus:'shipped'});expect(db.transactions.find(t=>t.id==='sale2')).toMatchObject({shipping:12.5,profit:107.5,deliveryStatus:'shipped',paidAmount:50});expect(db.products).toEqual(s.products);
 await nav(page,'tx');const expense=db.transactions.find(t=>t.shipmentId);await expect(page.locator(`[data-txedit="${expense.id}"]`)).toHaveCount(0);await page.locator(`[data-txdel="${expense.id}"]`).click();await expect(page.locator('#modal-message')).toContainText('ประวัติการส่งสินค้า');
});
test('shipping correction changes only the parcel share and zero removes expense restoring original sale costs',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('#shipment-select-all').check();await page.locator('#shipment-cost').fill('40');await send(page);await expectSaved(page,s=>s.shipments.length===1);await editCost(page,80);await expectSaved(page,s=>s.shipments[0].shippingCost===80);let db=await snapshot(page);expect(db.transactions.find(t=>t.id==='sale1')).toMatchObject({shipping:70,profit:380});expect(db.transactions.filter(t=>t.shipmentId)).toHaveLength(1);await editCost(page,0);await expectSaved(page,s=>s.shipments[0].shippingCost===0);db=await snapshot(page);expect(db.transactions.find(t=>t.id==='sale1')).toMatchObject({shipping:10,profit:440});expect(db.transactions.find(t=>t.id==='sale2')).toMatchObject({shipping:0,profit:120});expect(db.transactions.filter(t=>t.shipmentId)).toHaveLength(0);
});
test('partial shipment cancellation retains paid costs and reshipping with zero does not duplicate expenses',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('[data-pending-sale="sale1"] .shipment-select').check();await page.locator('#send-qty-sale1').fill('1');await page.locator('#shipment-cost').fill('30');await send(page);await expectSaved(page,s=>s.shipments.length===1);await page.locator('[data-shipment-cancel]').click();await page.locator('#modal-ok-btn').click();await expectSaved(page,s=>s.shipments[0].status==='cancelled');expect((await snapshot(page)).transactions.find(t=>t.id==='sale1')).toMatchObject({shipping:40,profit:410,deliveryStatus:'pending'});await page.locator('[data-pending-sale="sale1"] .shipment-select').check();await send(page);await expectSaved(page,s=>s.shipments.length===2);expect((await snapshot(page)).transactions.filter(t=>t.shipmentId)).toHaveLength(1);
});
test('bad cost and failed write leave all selected sales untouched; retry writes once',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('#shipment-select-all').check();await page.locator('#shipment-form').evaluate(f=>f.noValidate=true);for(const amount of ['-1','1.234']){await page.locator('#shipment-cost').fill(amount);await send(page);await expect(page.locator('#modal-message')).toContainText('ค่าส่งต้อง');await page.locator('#modal-ok-btn').click();}await page.locator('#shipment-cost').fill('50');await page.evaluate(()=>window.__testSaveError='offline');await send(page);await expect(page.locator('#modal-message')).toContainText('บันทึกไม่สำเร็จ');await page.locator('#modal-ok-btn').click();expect((await snapshot(page)).shipments).toHaveLength(0);await expect(page.locator('#shipment-cost')).toHaveValue('50');await page.evaluate(()=>delete window.__testSaveError);await send(page);await expectSaved(page,s=>s.shipments.length===1);expect((await snapshot(page)).transactions.filter(t=>t.shipmentId)).toHaveLength(1);
});
test('shipment cost backups retain allocations and reject mismatched or orphan expenses',async({page})=>{
 await boot(page,seed());await nav(page,'shipments');await page.locator('#shipment-select-all').check();await page.locator('#shipment-cost').fill('40');await send(page);await expectSaved(page,s=>s.shipments.length===1);const results=await page.evaluate(async()=>{const {validateShipments}=await import('/js/shipments.js');const s=structuredClone(window.__testDB),valid=()=>validateShipments(s.shipments,s.transactions);const r=[valid()];s.shipments[0].items[0].shippingShare=99;r.push(valid());s.shipments[0].items[0].shippingShare=30;s.transactions.find(t=>t.shipmentId).shipmentId='missing';r.push(valid());return r;});expect(results).toEqual([true,false,false]);
});
